export const dummy = {
    results: [
        {
            id: 1,
            photo: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            age: 2,
            gender: 1,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 2,
            photo: "https://www.ekara.org/file/getBlob/31986",
            name: "스틴",
            age: 2,
            gender: 1,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 3,
            photo: "https://www.ekara.org/file/getBlob/32250",
            name: "꿍얼",
            age: 5,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 4,
            photo: "https://www.ekara.org/file/getBlob/32244",
            name: "가달",
            age: 10,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 5,
            photo: "https://www.ekara.org/file/getBlob/31660",
            name: "또자",
            age: 7,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 6,
            photo: "https://www.ekara.org/file/getBlob/31822",
            name: "윌리",
            age: 1,
            gender: 1,
            species: "고양이",
            isAdopted: true,
        },
        {
            id: 7,
            photo: "https://www.ekara.org/file/getBlob/30018",
            name: "콧점",
            age: 8,
            gender: 3,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 8,
            photo: "https://www.ekara.org/file/getBlob/28299",
            name: "디아나",
            age: 4,
            gender: 3,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 9,
            photo: "https://www.ekara.org/file/getBlob/29662",
            name: "바마",
            age: 14,
            gender: 3,
            species: "강아지",
            isAdopted: true,
        },
        {
            id: 10,
            photo: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            age: 2,
            gender: 1,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 11,
            photo: "https://www.ekara.org/file/getBlob/31986",
            name: "스틴",
            age: 2,
            gender: 1,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 12,
            photo: "https://www.ekara.org/file/getBlob/32250",
            name: "꿍얼",
            age: 5,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 13,
            photo: "https://www.ekara.org/file/getBlob/32244",
            name: "가달",
            age: 10,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 14,
            photo: "https://www.ekara.org/file/getBlob/31660",
            name: "또자",
            age: 7,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 15,
            photo: "https://www.ekara.org/file/getBlob/31822",
            name: "윌리",
            age: 1,
            gender: 1,
            species: "고양이",
            isAdopted: true,
        },
        {
            id: 16,
            photo: "https://www.ekara.org/file/getBlob/30018",
            name: "콧점",
            age: 8,
            gender: 3,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 17,
            photo: "https://www.ekara.org/file/getBlob/28299",
            name: "디아나",
            age: 4,
            gender: 3,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 18,
            photo: "https://www.ekara.org/file/getBlob/29662",
            name: "바마",
            age: 14,
            gender: 3,
            species: "강아지",
            isAdopted: true,
        },
        {
            id: 19,
            photo: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            age: 2,
            gender: 1,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 20,
            photo: "https://www.ekara.org/file/getBlob/31986",
            name: "스틴",
            age: 2,
            gender: 1,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 21,
            photo: "https://www.ekara.org/file/getBlob/32250",
            name: "꿍얼",
            age: 5,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 22,
            photo: "https://www.ekara.org/file/getBlob/32244",
            name: "가달",
            age: 10,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 23,
            photo: "https://www.ekara.org/file/getBlob/31660",
            name: "또자",
            age: 7,
            gender: 2,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 24,
            photo: "https://www.ekara.org/file/getBlob/31822",
            name: "윌리",
            age: 1,
            gender: 1,
            species: "고양이",
            isAdopted: true,
        },
        {
            id: 25,
            photo: "https://www.ekara.org/file/getBlob/30018",
            name: "콧점",
            age: 8,
            gender: 3,
            species: "고양이",
            isAdopted: false,
        },
        {
            id: 26,
            photo: "https://www.ekara.org/file/getBlob/28299",
            name: "디아나",
            age: 4,
            gender: 3,
            species: "강아지",
            isAdopted: false,
        },
        {
            id: 27,
            photo: "https://www.ekara.org/file/getBlob/29662",
            name: "바마",
            age: 14,
            gender: 3,
            species: "강아지",
            isAdopted: true,
        },
    ]
}