export const dummy = {
    results: [
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
        {
            animal_idx: 1,
            imgUrl: "https://www.ekara.org/file/getBlob/31975",
            name: "리안",
            year: 2,
            month: 3,
            isGuessed: true,
            gender: "MALE",
            species: "고양이",
            isAdopted: true,
        },
    ]
}